In [ ]:
import composable.records as rec

In [ ]:
# Standard imports
import polars as pl
import polars.selectors as cs
import seaborn as sns
import numpy as np

# Preprocessing stuff
from sklearn.preprocessing import LabelEncoder

# Model selection stuff
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_validate, GridSearchCV

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
# Classic classifiers
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.multiclass import OneVsOneClassifier, OneVsRestClassifier
# Metrics to use on the test set
# metric(y_test, y_predict)
from sklearn.metrics import accuracy_score, balanced_accuracy_score, f1_score, precision_score, recall_score, roc_auc_score

## Problem 2: 
•	genre_train.csv (n = 8,000 samples) 
•	genre_test.csv (m = 2,000 samples).  
Notes:
•	The last column of the genre_train.csv data is the response, i.e., GENRE.  
•	The first column of the genre_test.csv dataset is an ID. Do not remove/delete this column.  You will be asked to submit a CSV file that contains the predictions for all observations in the genre_test.csv dataset.  The ID column is needed so that your predictions for each observation can be matched against the true genre for each song.
Task.  Build the best your best model and use it to predict the genres for the test data, documenting your work in a clean and easy to read notebook.

In [ ]:
(train2 := pl.read_csv("data/genre_train.csv"))

shape: (8_000, 192)
┌────────┬────────┬──────────┬──────────┬───┬──────────────┬─────────────┬─────────────┬───────────┐
│ PAR_TC ┆ PAR_SC ┆ PAR_SC_V ┆ PAR_ASE1 ┆ … ┆ PAR_2RMS_TCD ┆ PAR_3RMS_TC ┆ PAR_3RMS_TC ┆ GENRE     │
│ ---    ┆ ---    ┆ ---      ┆ ---      ┆   ┆ _10FR_VAR    ┆ D_10FR_MEAN ┆ D_10FR_VAR  ┆ ---       │
│ f64    ┆ f64    ┆ f64      ┆ f64      ┆   ┆ ---          ┆ ---         ┆ ---         ┆ str       │
│        ┆        ┆          ┆          ┆   ┆ f64          ┆ f64         ┆ f64         ┆           │
╞════════╪════════╪══════════╪══════════╪═══╪══════════════╪═════════════╪═════════════╪═══════════╡
│ 2.5788 ┆ 481.45 ┆ 76989.0  ┆ -0.12334 ┆ … ┆ 0.0000241    ┆ 0.0021769   ┆ 0.0000028   ┆ Pop       │
│ 2.4465 ┆ 637.73 ┆ 122580.0 ┆ -0.14995 ┆ … ┆ 0.000045     ┆ 0.0026449   ┆ 0.000006    ┆ Jazz      │
│ 2.7737 ┆ 447.09 ┆ 8531.9   ┆ -0.16128 ┆ … ┆ 0.0000729    ┆ 0.001883    ┆ 0.000007    ┆ Classical │
│ 2.5227 ┆ 498.42 ┆ 67935.0  ┆ -0.15206 ┆ … ┆ 0.0000652    ┆ 0.0018177   ┆ 0.000008    ┆ Jazz      │
│ 2.468  ┆ 667.05 ┆ 59358.0  ┆ -0.13854 ┆ … ┆ 0.0000135    ┆ 0.0017306   ┆ 0.0000012   ┆ Rock      │
│ …      ┆ …      ┆ …        ┆ …        ┆ … ┆ …            ┆ …           ┆ …           ┆ …         │
│ 2.5632 ┆ 699.21 ┆ 68767.0  ┆ -0.20852 ┆ … ┆ 0.0000408    ┆ 0.0015565   ┆ 0.000004    ┆ Classical │
│ 2.618  ┆ 521.35 ┆ 293040.0 ┆ -0.10926 ┆ … ┆ 0.0000283    ┆ 0.0         ┆ 0.0         ┆ Pop       │
│ 2.4158 ┆ 1200.7 ┆ 450500.0 ┆ -0.16268 ┆ … ┆ 0.0015239    ┆ 0.012158    ┆ 0.000317    ┆ Jazz      │
│ 2.4733 ┆ 1002.7 ┆ 182190.0 ┆ -0.14259 ┆ … ┆ 0.00001      ┆ 0.0         ┆ 0.0         ┆ Rock      │
│ 2.6438 ┆ 504.05 ┆ 88112.0  ┆ -0.13572 ┆ … ┆ 0.000076     ┆ 0.0021769   ┆ 0.000007    ┆ Jazz      │
└────────┴────────┴──────────┴──────────┴───┴──────────────┴─────────────┴─────────────┴───────────┘

In [ ]:
(X_music_train :=
 train2
 .drop('GENRE')
 .to_pandas()
)

,PAR_TC,PAR_SC,PAR_SC_V,PAR_ASE1,PAR_ASE2,PAR_ASE3,PAR_ASE4,PAR_ASE5,PAR_ASE6,PAR_ASE7,...,PAR_2RMS_TCD,PAR_3RMS_TCD,PAR_ZCD_10FR_MEAN,PAR_ZCD_10FR_VAR,PAR_1RMS_TCD_10FR_MEAN,PAR_1RMS_TCD_10FR_VAR,PAR_2RMS_TCD_10FR_MEAN,PAR_2RMS_TCD_10FR_VAR,PAR_3RMS_TCD_10FR_MEAN,PAR_3RMS_TCD_10FR_VAR
0,2.5788,481.45,76989.0,-0.12334,-0.11578,-0.11176,-0.10412,-0.10610,-0.11026,-0.11375,...,0.011002,0.002032,0.041056,0.000091,0.049627,0.000231,0.011265,0.000024,0.002177,0.000003
1,2.4465,637.73,122580.0,-0.14995,-0.14802,-0.13800,-0.12927,-0.12515,-0.12340,-0.12159,...,0.011283,0.002503,0.045159,0.000356,0.037388,0.000118,0.011897,0.000045,0.002645,0.000006
2,2.7737,447.09,8531.9,-0.16128,-0.15742,-0.15769,-0.14861,-0.13812,-0.12762,-0.12145,...,0.007184,0.001977,0.023864,0.000014,0.021595,0.000228,0.007505,0.000073,0.001883,0.000007
3,2.5227,498.42,67935.0,-0.15206,-0.14469,-0.12817,-0.11443,-0.10792,-0.10940,-0.11545,...,0.010739,0.003002,0.026536,0.000143,0.023445,0.000403,0.007456,0.000065,0.001818,0.000008
4,2.4680,667.05,59358.0,-0.13854,-0.13176,-0.12585,-0.11932,-0.11844,-0.12240,-0.12335,...,0.012980,0.001687,0.044163,0.000037,0.051064,0.000090,0.012615,0.000013,0.001731,0.000001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,2.5632,699.21,68767.0,-0.20852,-0.20988,-0.20399,-0.18910,-0.18022,-0.17113,-0.15910,...,0.010259,0.002213,0.041992,0.000111,0.041839,0.000373,0.008795,0.000041,0.001556,0.000004
7996,2.6180,521.35,293040.0,-0.10926,-0.10459,-0.10474,-0.10374,-0.11403,-0.13115,-0.12807,...,0.008680,0.000000,0.033997,0.000380,0.018275,0.000046,0.007314,0.000028,0.000000,0.000000
7997,2.4158,1200.70,450500.0,-0.16268,-0.15626,-0.14782,-0.14327,-0.14400,-0.15100,-0.15986,...,0.028345,0.010240,0.078210,0.000815,0.083042,0.002996,0.031978,0.001524,0.012158,0.000317
7998,2.4733,1002.70,182190.0,-0.14259,-0.13251,-0.12210,-0.10955,-0.10171,-0.10157,-0.10951,...,0.019592,0.000000,0.076441,0.000142,0.095869,0.000198,0.019200,0.000010,0.000000,0.000000
7999,2.6438,504.05,88112.0,-0.13572,-0.12795,-0.11768,-0.11238,-0.10961,-0.11300,-0.11620,...,0.006921,0.001841,0.032664,0.000213,0.028441,0.000455,0.007793,0.000076,0.002177,0.000007

In [ ]:
(y_music_train := 
 train2
 .select('GENRE')
 .to_numpy()
 .ravel())

array(['Pop', 'Jazz', 'Classical', ..., 'Jazz', 'Rock', 'Jazz'],
      shape=(8000,), dtype=object)

In [ ]:
(test2 := pl.read_csv("data/genre_test.csv"))

shape: (2_000, 192)
┌──────┬────────┬────────┬──────────┬───┬──────────────┬──────────────┬──────────────┬─────────────┐
│ id   ┆ PAR_TC ┆ PAR_SC ┆ PAR_SC_V ┆ … ┆ PAR_2RMS_TCD ┆ PAR_2RMS_TCD ┆ PAR_3RMS_TCD ┆ PAR_3RMS_TC │
│ ---  ┆ ---    ┆ ---    ┆ ---      ┆   ┆ _10FR_MEAN   ┆ _10FR_VAR    ┆ _10FR_MEAN   ┆ D_10FR_VAR  │
│ i64  ┆ f64    ┆ f64    ┆ f64      ┆   ┆ ---          ┆ ---          ┆ ---          ┆ ---         │
│      ┆        ┆        ┆          ┆   ┆ f64          ┆ f64          ┆ f64          ┆ f64         │
╞══════╪════════╪════════╪══════════╪═══╪══════════════╪══════════════╪══════════════╪═════════════╡
│ 1    ┆ 2.0149 ┆ 453.65 ┆ 30081.0  ┆ … ┆ 0.013426     ┆ 0.000215     ┆ 0.0041143    ┆ 0.0000309   │
│ 2    ┆ 2.4641 ┆ 1230.1 ┆ 118150.0 ┆ … ┆ 0.023521     ┆ 0.0000109    ┆ 0.0021986    ┆ 0.000001    │
│ 3    ┆ 2.6691 ┆ 663.93 ┆ 321010.0 ┆ … ┆ 0.017121     ┆ 0.000648     ┆ 0.0066503    ┆ 0.000101    │
│ 4    ┆ 3.1202 ┆ 356.8  ┆ 9544.4   ┆ … ┆ 0.0069007    ┆ 0.000165     ┆ 0.0040707    ┆ 0.0000821   │
│ 5    ┆ 2.631  ┆ 711.31 ┆ 595710.0 ┆ … ┆ 0.014988     ┆ 0.000407     ┆ 0.006117     ┆ 0.0000779   │
│ …    ┆ …      ┆ …      ┆ …        ┆ … ┆ …            ┆ …            ┆ …            ┆ …           │
│ 1996 ┆ 2.3382 ┆ 932.19 ┆ 208130.0 ┆ … ┆ 0.01588      ┆ 0.000223     ┆ 0.0050395    ┆ 0.000061    │
│ 1997 ┆ 2.4972 ┆ 407.32 ┆ 54601.0  ┆ … ┆ 0.0090231    ┆ 0.0000146    ┆ 0.0024816    ┆ 0.000002    │
│ 1998 ┆ 2.4926 ┆ 1149.2 ┆ 169460.0 ┆ … ┆ 0.024033     ┆ 0.0003684    ┆ 0.003951     ┆ 0.0000139   │
│ 1999 ┆ 2.7379 ┆ 783.57 ┆ 1.15e6   ┆ … ┆ 0.013029     ┆ 0.000212     ┆ 0.0035701    ┆ 0.0000124   │
│ 2000 ┆ 2.4879 ┆ 910.97 ┆ 249360.0 ┆ … ┆ 0.019048     ┆ 0.0000558    ┆ 0.005181     ┆ 0.000002    │
└──────┴────────┴────────┴──────────┴───┴──────────────┴──────────────┴──────────────┴─────────────┘

In [ ]:
(generic_cls2 :=
 Pipeline(steps = [
     ('scaler', StandardScaler()),
     ('classifier', None)  
 ])

)

Pipeline(steps=[('scaler', StandardScaler()), ('classifier', None)])

In [ ]:

(log_reg_grid :=
 {'classifier': [LogisticRegression(max_iter=10000),
                 OneVsRestClassifier(LogisticRegression(max_iter=10000)),
                 OneVsOneClassifier(LogisticRegression(max_iter=10000))
               ],
 }
)

{'classifier': [LogisticRegression(max_iter=10000),
  OneVsRestClassifier(estimator=LogisticRegression(max_iter=10000)),
  OneVsOneClassifier(estimator=LogisticRegression(max_iter=10000))]}

In [ ]:
(bayes_grid := 
    {'classifier': [GaussianNB(),
                 OneVsRestClassifier(GaussianNB()),
                  OneVsOneClassifier(GaussianNB())
               ],
 })

{'classifier': [GaussianNB(),
  OneVsRestClassifier(estimator=GaussianNB()),
  OneVsOneClassifier(estimator=GaussianNB())]}

In [ ]:
(QDA_grid := 
    {'classifier': [QuadraticDiscriminantAnalysis(),
                 OneVsRestClassifier(QuadraticDiscriminantAnalysis()),
                  OneVsOneClassifier(QuadraticDiscriminantAnalysis())
               ],
 }
)

{'classifier': [QuadraticDiscriminantAnalysis(),
  OneVsRestClassifier(estimator=QuadraticDiscriminantAnalysis()),
  OneVsOneClassifier(estimator=QuadraticDiscriminantAnalysis())]}

In [ ]:
(LDA_grid := 
    {'classifier': [LinearDiscriminantAnalysis(),
                 OneVsRestClassifier(LinearDiscriminantAnalysis()),
                  OneVsOneClassifier(LinearDiscriminantAnalysis())
               ],
 }
)

{'classifier': [LinearDiscriminantAnalysis(),
  OneVsRestClassifier(estimator=LinearDiscriminantAnalysis()),
  OneVsOneClassifier(estimator=LinearDiscriminantAnalysis())]}

In [ ]:
std_weights = ['uniform', 'distance']
std_metrics = ['minkowski', 'euclidean', 'manhattan']

In [ ]:
(knn_alone := {
    'classifier': [KNeighborsClassifier()],
    'classifier__n_neighbors': list(range(3, 12, 2)),
    'classifier__weights': std_weights,
    'classifier__metric': std_metrics,
    'classifier__p': [1, 2],  
})

{'classifier': [KNeighborsClassifier()],
 'classifier__n_neighbors': [3, 5, 7, 9, 11],
 'classifier__weights': ['uniform', 'distance'],
 'classifier__metric': ['minkowski', 'euclidean', 'manhattan'],
 'classifier__p': [1, 2]}

In [ ]:
(wrapped_knn := {
    'classifier': [
        OneVsRestClassifier(KNeighborsClassifier()),
        OneVsOneClassifier(KNeighborsClassifier())
    ],
    'classifier__estimator__n_neighbors': list(range(3, 12, 2)),
    'classifier__estimator__weights': std_weights,
    'classifier__estimator__metric': std_metrics,
    'classifier__estimator__p': [1, 2],
})

{'classifier': [OneVsRestClassifier(estimator=KNeighborsClassifier()),
  OneVsOneClassifier(estimator=KNeighborsClassifier())],
 'classifier__estimator__n_neighbors': [3, 5, 7, 9, 11],
 'classifier__estimator__weights': ['uniform', 'distance'],
 'classifier__estimator__metric': ['minkowski', 'euclidean', 'manhattan'],
 'classifier__estimator__p': [1, 2]}

In [ ]:
(knn_full_grid := [knn_alone, wrapped_knn])

[{'classifier': [KNeighborsClassifier()],
  'classifier__n_neighbors': [3, 5, 7, 9, 11],
  'classifier__weights': ['uniform', 'distance'],
  'classifier__metric': ['minkowski', 'euclidean', 'manhattan'],
  'classifier__p': [1, 2]},
 {'classifier': [OneVsRestClassifier(estimator=KNeighborsClassifier()),
   OneVsOneClassifier(estimator=KNeighborsClassifier())],
  'classifier__estimator__n_neighbors': [3, 5, 7, 9, 11],
  'classifier__estimator__weights': ['uniform', 'distance'],
  'classifier__estimator__metric': ['minkowski', 'euclidean', 'manhattan'],
  'classifier__estimator__p': [1, 2]}]

In [ ]:
(combined_grids2 := [log_reg_grid, bayes_grid, QDA_grid, LDA_grid] + knn_full_grid)

[{'classifier': [LogisticRegression(max_iter=10000),
   OneVsRestClassifier(estimator=LogisticRegression(max_iter=10000)),
   OneVsOneClassifier(estimator=LogisticRegression(max_iter=10000))]},
 {'classifier': [GaussianNB(),
   OneVsRestClassifier(estimator=GaussianNB()),
   OneVsOneClassifier(estimator=GaussianNB())]},
 {'classifier': [QuadraticDiscriminantAnalysis(),
   OneVsRestClassifier(estimator=QuadraticDiscriminantAnalysis()),
   OneVsOneClassifier(estimator=QuadraticDiscriminantAnalysis())]},
 {'classifier': [LinearDiscriminantAnalysis(),
   OneVsRestClassifier(estimator=LinearDiscriminantAnalysis()),
   OneVsOneClassifier(estimator=LinearDiscriminantAnalysis())]},
 {'classifier': [KNeighborsClassifier()],
  'classifier__n_neighbors': [3, 5, 7, 9, 11],
  'classifier__weights': ['uniform', 'distance'],
  'classifier__metric': ['minkowski', 'euclidean', 'manhattan'],
  'classifier__p': [1, 2]},
 {'classifier': [OneVsRestClassifier(estimator=KNeighborsClassifier()),
   OneVsOneClassifier(estimator=KNeighborsClassifier())],
  'classifier__estimator__n_neighbors': [3, 5, 7, 9, 11],
  'classifier__estimator__weights': ['uniform', 'distance'],
  'classifier__estimator__metric': ['minkowski', 'euclidean', 'manhattan'],
  'classifier__estimator__p': [1, 2]}]

In [ ]:
(folds := StratifiedKFold(n_splits=5, shuffle=True, random_state=1204))

StratifiedKFold(n_splits=5, random_state=1204, shuffle=True)

In [ ]:
(combined_grid_search2 := GridSearchCV(
    generic_cls2,
    combined_grids2,
    cv=folds,
    scoring='balanced_accuracy',
    n_jobs=-1,
    verbose=1  ))

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=1204, shuffle=True),
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('classifier', None)]),
             n_jobs=-1,
             param_grid=[{'classifier': [LogisticRegression(max_iter=10000),
                                         OneVsRestClassifier(estimator=LogisticRegression(max_iter=10000)),
                                         OneVsOneClassifier(estimator=LogisticRegression(max_iter=1000...
                         {'classifier': [OneVsRestClassifier(estimator=KNeighborsClassifier()),
                                         OneVsOneClassifier(estimator=KNeighborsClassifier())],
                          'classifier__estimator__metric': ['minkowski',
                                                            'euclidean',
                                                            'manhattan'],
                          'classifier__estimator__n_neighbors': [3, 5, 7, 9,
                                                                 11],
                          'classifier__estimator__p': [1, 2],
                          'classifier__estimator__weights': ['uniform',
                                                             'distance']}],
             scoring='balanced_accuracy', verbose=1)

In [ ]:
combined_grid_search2.fit(X_music_train, y_music_train)

Fitting 5 folds for each of 192 candidates, totalling 960 fits

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=1204, shuffle=True),
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('classifier', None)]),
             n_jobs=-1,
             param_grid=[{'classifier': [LogisticRegression(max_iter=10000),
                                         OneVsRestClassifier(estimator=LogisticRegression(max_iter=10000)),
                                         OneVsOneClassifier(estimator=LogisticRegression(max_iter=1000...
                         {'classifier': [OneVsRestClassifier(estimator=KNeighborsClassifier()),
                                         OneVsOneClassifier(estimator=KNeighborsClassifier())],
                          'classifier__estimator__metric': ['minkowski',
                                                            'euclidean',
                                                            'manhattan'],
                          'classifier__estimator__n_neighbors': [3, 5, 7, 9,
                                                                 11],
                          'classifier__estimator__p': [1, 2],
                          'classifier__estimator__weights': ['uniform',
                                                             'distance']}],
             scoring='balanced_accuracy', verbose=1)

In [ ]:
(cv_test_scores :=
    cross_validate(combined_grid_search2, X_music_train, y_music_train,
               cv=folds,
               scoring=metrics,
               verbose=1,
               n_jobs=-1,
               )
    >> rec.subset([f'test_{m}' for m in metrics])
    >> rec.map(np.mean)
)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed: 34.9min finished

{'test_accuracy': np.float64(0.9455),
 'test_balanced_accuracy': np.float64(0.9451033921399447),
 'test_f1_micro': np.float64(0.9455)}

In [ ]:
combined_grid_search2.best_params_

{'classifier': KNeighborsClassifier(),
 'classifier__metric': 'minkowski',
 'classifier__n_neighbors': 3,
 'classifier__p': 1,
 'classifier__weights': 'distance'}

In [ ]:
combined_grid_search2.best_estimator_

Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 KNeighborsClassifier(n_neighbors=3, p=1, weights='distance'))])

<font color = "orange">
The winning model for the genre dataset is kNN. Specifically the parameters with the kNN model are n_nieghbors of 3, p of 1 for minkowski since minkowski was the winning metric. And lastly the weight is the distance. I have a predicted genre csv below to compare to the test data if able. After testing we can compute scores, cross-validate, etc. to really see how good this model was. Since we had 8000 observations in the training dataset I would want to think this would be a pretty good model in testing.
</font>

## Predicting Missing Genres

In [ ]:
# Predict genres for the test data
X_music_test = test2.drop("id").to_pandas()

In [ ]:

test_preds = combined_grid_search2.best_estimator_.predict(X_music_test)

In [ ]:
(genre_pred := pl.DataFrame({
    "id": test2["id"],
    "GENRE": test_preds
}))

shape: (2_000, 2)
┌──────┬───────────┐
│ id   ┆ GENRE     │
│ ---  ┆ ---       │
│ i64  ┆ str       │
╞══════╪═══════════╡
│ 1    ┆ Classical │
│ 2    ┆ Rock      │
│ 3    ┆ Blues     │
│ 4    ┆ Jazz      │
│ 5    ┆ Jazz      │
│ …    ┆ …         │
│ 1996 ┆ Classical │
│ 1997 ┆ Pop       │
│ 1998 ┆ Rock      │
│ 1999 ┆ Rock      │
│ 2000 ┆ Blues     │
└──────┴───────────┘

In [ ]:
genre_pred.head()

shape: (5, 2)
┌─────┬───────────┐
│ id  ┆ GENRE     │
│ --- ┆ ---       │
│ i64 ┆ str       │
╞═════╪═══════════╡
│ 1   ┆ Classical │
│ 2   ┆ Rock      │
│ 3   ┆ Blues     │
│ 4   ┆ Jazz      │
│ 5   ┆ Jazz      │
└─────┴───────────┘

In [ ]:
genre_pred.write_csv("data/genre_predictions.csv")